server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/textdb?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.imooc.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
# 通用 Mapper 配置
mapper:
  mappers: com.wondersgroup.easyexcel.stu.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true  #\u683C\u5F0F\u5316SQL,\u5982\u679C\u4E0D\u52A0,SQL\u8F93\u51FA\u4E0D\u6362\u884C,\u4E0D\u65B9\u4FBF\u67E5\u770B
#  kafka:
#    bootstrap-servers: 192.168.1.128:9092
#    listener:
#      concurrency: 10
#      ack-mode: MANUAL_IMMEDIATE
#      poll-timeout: 1500
#    consumer:
#      group-id: logSystem
#      enable-auto-commit: false
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties: { session.timeout.ms: 6000, auto.offset.reset: earliest }
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      batch-size: 65536
#      buffer-memory: 524288

